// @ts-ignore: generated by `opennextjs-cloudflare build`, resolved by wrangler
import nextWorker from "./.open-next/worker.js";
import { serveWithEdgeCache, VERSION_KEY, type StoredPage } from "./lib/edge-page-cache";

// @ts-ignore: generated by `opennextjs-cloudflare build`, resolved by wrangler
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";

interface Env {
    SESSION_KV: KVNamespace;
    PAGE_CACHE: R2Bucket;
}

export default {
    async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
        return serveWithEdgeCache(
            request,
            {
                cache: (caches as unknown as { default: Cache }).default,
                store: {
                    async get(key) {
                        const obj = await env.PAGE_CACHE.get(key);
                        if (!obj) return null;
                        const meta = obj.customMetadata ?? {};
                        return {
                            body: await obj.text(),
                            contentType: meta.contentType ?? "text/html; charset=utf-8",
                            renderedAt: Number(meta.renderedAt ?? 0),
                        };
                    },
                    put: (key, page: StoredPage) =>
                        env.PAGE_CACHE.put(key, page.body, {
                            customMetadata: {
                                contentType: page.contentType,
                                renderedAt: String(page.renderedAt),
                            },
                        }),
                },
                readVersion: () => env.SESSION_KV.get(VERSION_KEY),
                waitUntil: (p) => ctx.waitUntil(p),
            },
            () => nextWorker.fetch(request, env, ctx),
        );
    },
};
