name = "cf-blog"
main = ".open-next/worker.js"
compatibility_date = "2026-04-30"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cf-blog-bucket"

[vars]
TEAM_DOMAIN = "" # Set your Cloudflare Access team domain (e.g., your-team.cloudflareaccess.com)
POLICY_AUD = "" # Set your Cloudflare Access policy audience