/**
 * Generates lib/tools.ts from API route annotations
 * Run: node scripts/generate-tools.js
 */
import { readdir, writeFile, readFile } from 'fs/promises';
import { join } from 'path';

const TOOLS_DIR = 'app/api';
const OUTPUT_FILE = 'lib/tools.ts';

const TOOL_ANNOTATION = '// @tool';

async function extractToolFromRoute(filePath) {
  const content = await readFile(filePath, 'utf-8');

  const match = content.match(/\/\/\s*@tool\s+(\S+)\s+-\s+(.+)/);
  if (!match) return null;

  const exampleMatch = content.match(/\/\/\s*@tool-example\s+(.+)/);

  return {
    name: match[1],
    description: match[2],
    example: exampleMatch ? exampleMatch[1] : '',
  };
}

async function generateTools() {
  const apiDir = join(process.cwd(), TOOLS_DIR);
  const entries = await readdir(apiDir, { withFileTypes: true });

  const tools = [];

  for (const entry of entries) {
    if (entry.name === 'route.ts') continue;

    const routePath = join(apiDir, entry.name, 'route.ts');
    try {
      const tool = await extractToolFromRoute(routePath);
      if (tool) tools.push(tool);
    } catch {
      // skip
    }
  }

  const content = `/**
 * Auto-generated tool registry
 * Generated by scripts/generate-tools.ts
 * Do not edit manually
 */

export interface Tool {
  name: string;
  description: string;
  example: string;
}

export const TOOLS: Tool[] = ${JSON.stringify(tools, null, 2)} as const;
`;

  await writeFile(join(process.cwd(), OUTPUT_FILE), content);
  console.log(`Generated ${tools.length} tools → ${OUTPUT_FILE}`);
}

generateTools().catch(console.error);