/**
 * Reads all fastfetch small logo files from public/fastfetch-logos/
 * and generates lib/logos.generated.ts so the data is bundled at
 * build time — no runtime HTTP fetch needed.
 */
import { readFileSync, writeFileSync, readdirSync } from "fs";
import { join } from "path";

const LOGO_DIR = new URL("../public/fastfetch-logos", import.meta.url);
const OUT = new URL("../lib/logos.generated.ts", import.meta.url);

const files = readdirSync(LOGO_DIR).filter((f) => f.endsWith(".txt"));

const entries = files.map((f) => {
    const text = readFileSync(join(LOGO_DIR.pathname, f), "utf-8");
    // Escape backticks and backslashes for a template-literal value.
    // $ without { is safe inside template literals ($1 … $5 are literal).
    const escaped = text.replace(/\\/g, "\\\\").replace(/`/g, "\\`");
    return `  "${f}": \`${escaped}\``;
});

const code = `// Generated by scripts/generate-logos.mjs — do not edit manually.
// Source files: public/fastfetch-logos/*.txt

const LOGOS: Record<string, string> = {\n${entries.join(",\n")},\n} as const;

export function getLogoText(filename: string): string {
  return LOGOS[filename] ?? "";
}
`;

writeFileSync(OUT, code, "utf-8");
console.log(`✓ Generated lib/logos.generated.ts (${files.length} logos)`);
