"""Writes src/lib/audio/body-irs.ts: every body the IR module can play, each
measured from recordings (see body.py). Run after changing the list:

    source env.sh && uv run make_irs.py
"""
import base64, glob, os, numpy as np
from body import response, min_phase_ir

HERE = os.path.dirname(os.path.abspath(__file__))
V = os.path.join(HERE, '.cache/refs/vsco')
OUT = os.path.join(HERE, '../../src/lib/audio/body-irs.ts')

# label (4 chars at most, it is a picker entry), what it is, the recordings, the source's fall.
BODIES = [
    ('VLN', 'violin section', 'Strings/Violin Section/susVib/*.wav', 1.0),
    ('VLA', 'viola section', 'Strings/Viola Section/susvib/*.wav', 1.0),
    ('CELL', 'cello section', 'Strings/Cello Section/susvib/*.wav', 1.0),
    ('CLAR', 'clarinet', 'Woodwinds/Clarinet/susLong/*.wav', 1.0),
    ('BASS', 'double bass', 'Strings/Solo Contrabass/SusVib/*.wav', 1.0),
    # Plucked: the first quarter second, against a pluck's 1/n^2.
    ('VPZ', 'violin section, pizzicato', 'Strings/Violin Section/Pizz/*rr1.wav', 2.0, False, 0.01, 0.25),
    ('CPZ', 'cello section, pizzicato', 'Strings/Cello Section/pizzT/*RR1.wav', 2.0, False, 0.01, 0.25),
]
N = 4096

rows = []


def iowa_piano_notes():
    from realplay import iowa_piano, note_audio
    return [(m, note_audio(p)) for m, p in sorted(iowa_piano('mf').items())]


for label, what, pattern, slope, *more in BODIES:
    odd, t0, t1 = (list(more) + [False, 0.3, None])[:3] if len(more) < 3 else more
    files = sorted(glob.glob(os.path.join(V, pattern)))
    g, d = response(files, source_slope=slope, odd=bool(odd), t0=t0, t1=t1)
    h = min_phase_ir(g, d, n=N)
    q = np.round(h / np.abs(h).max() * 32767).astype('<i2')
    scale = float(np.abs(h).max())
    rows.append((label, what, len(files), scale, base64.b64encode(q.tobytes()).decode()))
    print(label, len(files), 'files')

# The piano's board: the Iowa MIS Steinway (free to use), every mf key, the
# first second after the strike against a struck string's 1/n^1.5.
from body import response_from
notes = iowa_piano_notes()
g, d = response_from(notes, source_slope=1.5, t0=0.05, t1=1.0)
h = min_phase_ir(g, d, n=N)
q = np.round(h / np.abs(h).max() * 32767).astype('<i2')
rows.append(('PNO', 'grand piano soundboard (Iowa MIS Steinway, mf)', len(notes), float(np.abs(h).max()), base64.b64encode(q.tobytes()).decode()))
print('PNO', len(notes), 'notes')

with open(OUT, 'w') as f:
    f.write('''/**
 * The bodies the IR module can put a sound through, each measured from
 * recordings rather than drawn: the level of every harmonic of every note,
 * divided by what the string itself puts there, pooled into one response and
 * turned into a minimum-phase impulse. What makes a bowed saw a violin is
 * this -- dozens of resonances and dips a few EQs cannot draw, which the
 * partials cross as the pitch moves.
 *
 * GENERATED by tools/ear/make_irs.py from the VSCO-2 Community Edition
 * samples (CC0) and the University of Iowa MIS piano (free to use). Do not
 * edit by hand.
 */
export interface BodyIr {
	/** The picker's name for it, four characters at most. */
	label: string;
	/** What was recorded. */
	what: string;
	/** Samples per second of `data`. */
	rate: number;
	/** Peak of the impulse before it was scaled to 16 bits. */
	scale: number;
	/** Little-endian 16-bit samples, base64. */
	data: string;
}

export const BODY_IRS: BodyIr[] = [
''')
    for label, what, n, scale, data in rows:
        f.write(f"\t{{ label: '{label}', what: '{what} ({n} notes)', rate: 48000, scale: {scale:.6g}, data: '{data}' }},\n")
    f.write('];\n')
print('wrote', OUT, os.path.getsize(OUT), 'bytes')
