name = "cf-blog-cache"
main = "src/index.ts"
compatibility_date = "2026-04-30"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "cf-blog-db"
database_id = "f763e00a-1c8b-42d4-ad4f-65d0136cabd2"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cf-blog-bucket"

[[vectorize]]
binding = "SEARCH_INDEX"
index_name = "blog-search"

[triggers]
crons = ["*/30 * * * *", "*/3 * * * *"]

[vars]
CRON_SECRET = ""
GH_USERNAME = "kurashizu"
